### ISSUE TITLE
ModuleNotFoundError: No module named 'cmake'

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [zassou65535/VITS#3]
When I tried to build this repository, the following error occurred.

```
$ pip install -r requirements.txt
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting audioread==2.1.9
  Using cached audioread-2.1.9.tar.gz (377 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting charset-normalizer==2.0.10
  Using cached charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
Collecting cycler==0.11.0
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting Cython==0.29.26
  Using cached Cython-0.29.26-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Collecting decorator==5.1.0
  Using cached decorator-5.1.0-py3-none-any.whl (9.1 kB)
Collecting fonttools==4.28.5
  Using cached fonttools-4.28.5-py3-none-any.whl (890 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting kiwisolver==1.3.2
  Using cached kiwisolver-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting librosa==0.8.1
  Using cached librosa-0.8.1-py3-none-any.whl (203 kB)
Collecting llvmlite==0.37.0
  Using cached llvmlite-0.37.0-cp38-cp38-manylinux2014_x86_64.whl (26.3 MB)
Collecting matplotlib==3.5.1
  Using cached matplotlib-3.5.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Collecting numba==0.54.1
  Using cached numba-0.54.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
Collecting numpy==1.22
  Using cached numpy-1.22.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting packaging==21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting Pillow>=9.0.0
  Using cached Pillow-9.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting pooch==1.5.2
  Using cached pooch-1.5.2-py3-none-any.whl (57 kB)
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pyopenjtalk==0.1.5
  Using cached pyopenjtalk-0.1.5.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ishihara/VITS/Vits/bin/python /tmp/tmpwy3_2sff get_requires_for_build_wheel /tmp/tmplh_9p_po
       cwd: /tmp/pip-install-o3a7e24s/pyopenjtalk
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/home/ishihara/VITS/Vits/bin/cmake", line 5, in <module>
      from cmake import cmake
  ModuleNotFoundError: No module named 'cmake'
  <string>:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  Traceback (most recent call last):
    File "/tmp/tmpwy3_2sff", line 280, in <module>
      main()
    File "/tmp/tmpwy3_2sff", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpwy3_2sff", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-4y0bjojz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-4y0bjojz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-4y0bjojz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-4y0bjojz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 154, in <module>
    File "/usr/lib/python3.8/subprocess.py", line 448, in check_returncode
      raise CalledProcessError(self.returncode, self.args, self.stdout,
  subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ishihara/VITS/Vits/bin/python /tmp/tmpwy3_2sff get_requires_for_build_wheel /tmp/tmplh_9p_po Check the logs for full command output.
(Vits) ishihara@ishihara-OptiPlex-7010:~/VITS/VITS$ python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmake
>>> from cmake import cmake
>>> exit()
(Vits) ishihara@ishihara-OptiPlex-7010:~/VITS/VITS$ cmake--version
cmake--version: コマンドが見つかりません
(Vits) ishihara@ishihara-OptiPlex-7010:~/VITS/VITS$ cmake --version
cmake version 3.25.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
It is sayinng that "ModuleNotFoundError: No module named 'cmake'".
But I did "sudo apt install cmake" and "pip install cmake".
Please let me know how to fix it.

**Comment by zassou65535** [comment]
There were some old libraries listed in requirements.txt, so I updated it. Please try again.
