### ISSUE TITLE
Renewal repository has ImportError

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [zassou65535/VITS#5]
Today, I cloned the renewal repository, but jvs_preprocessor.py maked the following error.

```
$ python3 jvs_preprocessor.py
Traceback (most recent call last):
  File "__init__.pxd", line 945, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jvs_preprocessor.py", line 10, in <module>
    import pyopenjtalk
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyopenjtalk/__init__.py", line 20, in <module>
    from .htsengine import HTSEngine
  File "pyopenjtalk/htsengine.pyx", line 8, in init pyopenjtalk.htsengine
  File "__init__.pxd", line 947, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

The environment is as follows:
ubuntu:20.04.1
python:3.8.5
torch:1.10.1+cu113 
torchaudio:0.10.1+cu113
numpy:1.22.0

**Comment by zassou65535** [comment]
Some of the libraries was out of date, so I rewrote requirements.txt and modified some codes accordingly. Please try again.

**Comment by Ishihara-Masabumi** [comment]
Thanks. It's OK.
